### ISSUE TITLE
Computers Sentence

### ISSUE THREAD

**Issue by vincenzocalabrese** [imperva/domain-directory-controller#5]
Hello,
is possibile to manage a different sentence for different Object type like a computers?
In this moment, at version 7.3.0.0.0.0, I've see that only users or groups are managed.

Thanks,
Vincenzo

**Comment by gabibeyo** [comment]
Hello Vincenzo,
I am not 100% sure I understand your use case.

maybe you can share the query and explain what you are trying to do?

Thanks

**Comment by gabibeyo** [comment]
Regarding the first question:
Computer and Printers are supported as well.
In the 'value' field instead of 'user', 'group' you can type in any valid OBJECT_CLASS value.
You can see here the list of supported values:
https://docs.microsoft.com/en-us/windows/desktop/ADSchema/classes-all 

For the second question, I still don't get the problem you are facing.
